language: generic

sudo: required
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - secure: "o6i3zzU4kZgYJC9x86MIm3pNtD99ZRcc69UOb5zJeDpYDGLFoLwIptRX7eCBdgHhm1kcgbFGpe+vCNqAFsXfZJx81UM1nf8oe7NRC9ppp5KtspySBOczGGsiDcvhaDVAj7iwyV6ksE0U51G8NN6A2fsvzJV8OZ9rVEOex+WLjIZJ7yLwGGvgYDI7X0a4+QV5tq7a31g7/p0tfs4jdvN43ye9u/7DlS3ptzlQaqbCyCfO4vM18hJt2zy9VzRJy4LD51CdmQQfdHcJYH2kThg6RtmgjvZ1tvx3HoKRO4w58WKLlCkGNWIRu2YFt5Jc2la1IPfQ2KXN8tddslwqueZlbec+4rWiAdUZkS5IMzbSYOWjrHiFsRdppdAd4CNcRJJlXKGaJOHJ3kOeQ329pn9koXj5y73Uu7zJwisXcHZcECT77KsKNJyAhEgZ41NYQVYNVLzA29InfRc0qYoXSpzOJgJSJ+EpsmDvYX8Y1RMkqO+Nt1qY0V6P+OC6T18yWvXAA3KH4RQW7Dh2Oaec8Ee1VCmKChrDAF5sD+LNbkPZyG5KlQ+Rn47k5lbCpbRTQzx34+EbytAdMXNHRRGVoQP7UXitqmqlcuuqbrzgjGL9/2t7kfSJ5XLeXrfYLIGP2xtqf/x4tpEprs8YdT+47Kz0HpYUdG8vFR6+igiyJEMQdo4="

addons:
  apt:
    packages:
    - gettext
    - libunwind8
    - libicu52

before_install:
  - curl -sSL -o dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-linux-x64.tar.gz
  - sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
  - sudo ln -s /opt/dotnet/dotnet /usr/local/bin

script:
  - dotnet pack src/Tmds.Babeltrace --configuration Release --version-suffix "$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER" --output .
  - dotnet pack src/Tmds.DotnetTrace.Tool --configuration Release --version-suffix "$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER" --output .

after_success:
  - 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/Tmds.Babeltrace/Tmds.Babeltrace.*.nupkg https://www.myget.org/F/tmds/api/v2/package ;
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/Tmds.DotnetTrace.Tool/Tmds.DotnetTrace.Tool.*.nupkg https://www.myget.org/F/tmds/api/v2/package ;
     fi'
